### ISSUE TITLE
fft analysis?!

### ISSUE THREAD

**Issue by joaodafonseca** [admsyn/ofxAudioUnit#1]
hi there is it possible to do some audio FFT analysis with ofxAudioUnit??

**Comment by polyren** [comment]
@admsyn

Hi! I'm trying to use ofxAudioUnitFftNode to analysis FFT, but I found that you have removed the tree fft example. Where can I find it?

**Comment by stephanschulz** [comment]
@admsyn do you think you have a simple FFT example kicking around that would help me understand how to set the bin size and extra the values from each FFT bin?
thx

**Comment by stephanschulz** [comment]
would this be enough? seems a bit jumpy with the mic input.
```
 fft.setFftBufferSize(12);
 input.connectTo(tap).connectTo(fft).connectTo(output);

```
```
vector<float> outAmplitude;
    fft.getAmplitude(outAmplitude);
    
    int ww = 20;
    ofPushMatrix();
    ofTranslate(100,300);
    for(int i=0; i<outAmplitude.size(); i++){
        ofDrawRectangle(i*ww,0,ww,-outAmplitude[i]*100);
    }
    ofPopMatrix;
```

**Comment by admsyn** [comment]
Hey Stephan, you probably want `.setFftBufferSize()` to be more like `512` or `1024`, and you could try experimenting with the scale as well.
