### ISSUE TITLE
Use it with array

### ISSUE THREAD

**Issue by dferrandizmont** [admsyn/ofxAudioUnit#14]
Hi, for one work I would like to use this addon but I need to load an array of sounds (33 exactly). 

How can I do it? Because if I do it at the same way I do with ofSoundPlayer (ofSoundPlayer sound[ NSOUNDS ];) with the #define NSOUNDS 33; at the top of the page it doesn't work . 

Then, I think I need to use an array with output too, right?

This is how I have it right now with soundPlayer (setup();)

```
for ( int i=0; i<NSOUNDS; i++) {
sound[i].loadSound("Sounds/" + ofToString( i + 1 ) + ".wav" );
}
```

and in draw() I have the .play()

```
 for ( int i=0; i<NSOUNDS; i++) {
     int ran = ofRandom(33);
     if (doOnce == true){
         sound[ran].play();
         sound[ran].setLoop(true);
     }
```

How can I translate all that code to make it work with the addon?

Thank you so much.

**Comment by Wenzy--** [comment]
Hi Adam, I am using of_v0.9.0_ios_release and trying to use the ofxAudioUnitSampler on ios9 but when I initialize the unit the way I do on OSX like this:
```sampler = ofxAudioUnitSampler('aumu', 'dls ', 'appl');```
I'm receiving this error:
```Couldn't locate component for description: aumu, dls , appl```

I saw that you mentioned that the builtin audio units on ios are not the same as on osx.  How can I find out what audio units are available on my device? Is there an equivalent of ```auval -a``` for ios?

**Comment by dimitre** [comment]
Hello @admsyn , I'm writing in here because it mentioned using with array.
I'm using inside an object, and I've noticed some functionalities are working when using arrays but not working when using vectors.

I'm using each object to forward audio to Logic using AUNetSender, in a different address.
When I create a normal object or array, it plays allright and the server name is OK (AREIA0, AREIA1)
but when using with vectors I have no audio and a generic name for the server.

```c++
	struct play {
		public:
		ofxAudioUnitFilePlayer source;
		ofxAudioUnit varispeed;
		ofxAudioUnitMixer mixerPan;
		ofxAudioUnitNetSend send;
		
		ofxAudioUnitMixer mixerOut;
		ofxAudioUnitOutput output;
		ofxAudioUnitTap tap;
		play() {
			int index = 0;
			string sendName = "AREIA" + ofToString(index);
			cout << sendName << endl;
			send.setName(sendName);
			
			varispeed.setup(kAudioUnitType_FormatConverter, kAudioUnitSubType_Varispeed);
			AudioUnitSetParameter(varispeed,
								  kVarispeedParam_PlaybackRate,
								  kAudioUnitScope_Global,
								  0, 1.0, 0);
			
			source.connectTo(varispeed).connectTo(mixerPan).connectTo(send).connectTo(mixerOut).connectTo(output);
			mixerPan.setOutputVolume(1);
			mixerOut.setOutputVolume(1);
			output.start();
			source.setFile("/Volumes/werk/AREIA_AUDIO/dmtrnick1.aif");
			source.loop();
		}
	};
```

Thank you!
