### ISSUE TITLE
Reverb on iOS

### ISSUE THREAD

**Issue by dferrandizmont** [admsyn/ofxAudioUnit#19]
Hi, i'm trying to use a reverb effect on iOS and I can't. My problem is that I can't set the  ``` kReverb2Param_DryWetMix``` to 0 (default is 100%) and when the sound starts it starts with reverb, and my second problem is that if I write 

   ```float newReverb = ofMap(touch.x, 0, ofGetWidth(), 0, 100, true);```
	
	AudioUnitSetParameter(reverb.getUnit(),
						  kReverb2Param_DryWetMix,
						  kAudioUnitScope_Global,
						  0,
						  newReverb,
						  0)

the ``` kReverb2Param_DryWetMix``` doesn't change it value and I don't know why. 

Thanks.

**Comment by admsyn** [comment]
Going to close this, but thanks for the report! Managing the parameters for iOS-specific units is out of the scope of the addon I feel.
