### ISSUE TITLE
XCode 7

### ISSUE THREAD

**Issue by stswong** [admsyn/ofxAudioUnit#25]
I made the mistake of going to XCode 7 yesterday. Now ofxAudioUnit won't compile. I made a blank project with of_v20150909_osx_release and it compiled and ran fine. I then added ofxAudioUnit to the AddOn folder, and it failed to compile with the errors "gltypes.h included before glew.h" and "error: typedef redefinition with differen ttypes...".

Wondering if anyone has similar problems.

Thanks.
Sam

**Comment by jasonlevine** [comment]
Sounds more like an openframeworks 0.9 + Xcode 7 problem than a
ofxAudioUnit problem.  Have you tried OF0.8.4 + Xcode 7 with ofAudioUnit?

On Thu, Sep 17, 2015 at 3:59 PM, stswong <notifications@github.com> wrote:

> I made the mistake of going to XCode 7 yesterday. Now ofxAudioUnit won't
> compile. I made a blank project with of_v20150909_osx_release and it
> compiled and ran fine. I then added ofxAudioUnit to the AddOn folder, and
> it failed to compile with the errors "gltypes.h included before glew.h" and
> "error: typedef redefinition with differen ttypes...".
>
> Wondering if anyone has similar problems.
>
> Thanks.
> Sam
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/admsyn/ofxAudioUnit/issues/25>.
>



-- 
Jason Levine
new media performer + creative coder
*https://www.behance.net/jasonlevine <https://www.behance.net/jasonlevine>*

**Comment by stswong** [comment]
I was on OF0.8.4 + XCode 6 to begin with. When I updated to XCode 7, it complained about openssl problem. Web searching pointed me to OF0.9 to fix this issue, but then the gltypes.h/glew.h problem appeared.

Any help on the openssl issue?
Thanks.

**Comment by jasonlevine** [comment]
But it worked with OF0.8.4 + XCode 6, correct?  Xcode 7 is probably
assuming you are running osx10.11.  Find any incidences of 10.11 in you
build settings an change them to 10.10 or whatever system you are running.
The  gltypes.h/glew.h problem sounds like a change in the OF core
which ofxAudioUnit
is probably not caught up to.

@admsym can you comment on ofxAudioUnit OF0.9.0 compatibility?

On Thu, Sep 17, 2015 at 4:40 PM, stswong <notifications@github.com> wrote:

> I was on OF0.8.4 + XCode 6 to begin with. When I updated to XCode 7, it
> complained about openssl problem. Web searching pointed me to OF0.9 to fix
> this issue, but then the gltypes.h/glew.h problem appeared.
>
> Any help on the openssl issue?
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/admsyn/ofxAudioUnit/issues/25#issuecomment-141221987>.
>



-- 
Jason Levine
new media performer + creative coder
*https://www.behance.net/jasonlevine <https://www.behance.net/jasonlevine>*

**Comment by stswong** [comment]
Yup, it has been working great with OF0.8.4 + XCode 6. I have been targeting for 10.6 and now 10.7. I am currently downloading XCode 6.4...

**Comment by stswong** [comment]
I'm back to OF0.8.4 + XCode 6 and everything works again! I copied my code to OF0.9.0 and with the latest ofxAudioUnit and it works too. So going to XCode 7 caused two problems:

openssl.h problem in OF0.9.0 itself
glew.h problem in ofxAudioUnit

Thanks.

**Comment by admsyn** [comment]
I was just dealing with that today, upgrading OFXcodeMenu! I'll look into it, but it's really weird :)

**Comment by admsyn** [comment]
Alright, looks like there was some new weird behaviour happening with the Objective-C++ compilation necessary for the `ofxAudioUnit::showUI(...)` function. Reworked the inclusion hierarchy to be a little bit cleaner, so gltypes.h / glew.h never enter the picture.

Let me know if you still see the issue, but it looks fixed to me!

**Comment by stswong** [comment]
It all compiles and works now, OF0.9 and Xcode 7.

Thanks.
Sam.
