### ISSUE TITLE
#include <tr1/memory> error

### ISSUE THREAD

**Issue by jeppius** [admsyn/ofxAudioUnit#26]
I get the "tr1/memory file not found error" 
on OsX, Xcode 6.1
base SDK  OSX 10.10
As C++ standard library I use libc++
Any hints?

**Comment by jasonlevine** [comment]
What version of OF? Use 0.9.0 if you can.

On Monday, January 25, 2016, jeppius <notifications@github.com> wrote:

> I get the "tr1/memory file not found error"
> on OsX, Xcode 61
> base SDK OSX 1010
> As C++ standard library I use libc++
> Any hints?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/admsyn/ofxAudioUnit/issues/26>.
>


-- 
Jason Levine
new media performer + creative coder
*https://www.behance.net/jasonlevine <https://www.behance.net/jasonlevine>*

**Comment by microcosm** [comment]
I haven't actually tested this against 0.9.0, only 0.8.4

**Comment by admsyn** [comment]
You may need to use libstdc++ if you're using OF 0.8, check out https://github.com/openframeworks/openFrameworks/pull/2764

Do you get the error if you don't have ofxAudioUnit in your project?

**Comment by jeppius** [comment]
Ok, 0.8.4 because I was trying to still use ofxUI ...I'll switch to 0.9.0 then, thanks.
