### ISSUE TITLE
ofw 10.1 compatibility

### ISSUE THREAD

**Issue by dimitre** [admsyn/ofxAudioUnit#36]
Hello, I've noticed it isn't working in OFW 10.1, and I could fix the first issues by adding this two lines to ofxAudioUnit.cpp

```c++
#include "ofFileUtils.h"
```

```c++
template<typename T> using ofPtr = shared_ptr<T>;
```

but now it seems to complay of ofPolyline
```
/Volumes/tool/of_v0.10.1_osx_release/libs/openFrameworks/graphics/ofGraphicsBaseTypes.h:42:7: Typedef redefinition with different types ('ofPolyline_<ofDefaultVertexType>' (aka 'ofPolyline_<tvec3<float, highp> >') vs 'ofPolyline')
```

it would be great to have it running on 10.1
Thank you

**Comment by admsyn** [comment]
hey @dimitre, give it a try now. Last two commits should fix it!

**Comment by dimitre** [comment]
beautiful! thank you very much
